// Lesson 29 — What Is Real Online Now
// Arc: Judgment & Safety
// Ported from Core 50 (auto-generated, then reviewed). Edit here, then run tools/build-lessons.mjs
export default {
  "id": "chapter-29",
  "num": 29,
  "arc": "Judgment & Safety",
  "title": "What Is Real Online Now",
  "coreQuestion": "How do I decide what to trust online when anything could be AI-made?",
  "blurb": "Stop trusting \"it looks real.\" Run a three-question trust check on who shared it and whether a second source confirms it.",
  "minutes": 9,
  "resources": [],
  "steps": [
    {
      "kind": "coldOpen",
      "title": "The flawless post",
      "scenario": "You scroll past a photo of a famous politician saying something shocking. The lighting is perfect. The voice matches. Thousands of people are already sharing it, furious. It feels completely real. The next day it turns out none of it happened — the whole clip was generated by AI.",
      "prompt": "Before you read on: if the clip looked and sounded flawless, what could you have checked to catch it — without relying on how real it looked?"
    },
    {
      "kind": "reveal",
      "title": "\"Looks real\" stopped being evidence",
      "body": "Image, audio, and video generators learn patterns from large collections of media and can produce convincing new material. A polished photo, familiar voice, news-style clip, or five-star review can therefore be synthetic, edited, or taken out of context. Appearance alone is weak evidence. Decide how much to trust a consequential claim by tracing the original publisher, checking what evidence it provides, and finding independent confirmation.",
      "mistake": "Trusting a post because the details are perfect and it feels authentic — treating \"looks real\" as proof.",
      "good": "Treating every post as possibly AI-made, then checking the source and looking for a second, independent confirmation before you believe or share."
    },
    {
      "kind": "classify",
      "title": "Which clue actually helps?",
      "prompt": "Sort each thing into whether it's real evidence for trusting content, or a weak clue that proves nothing.",
      "buckets": [
        "Real evidence",
        "Weak clue / proves nothing"
      ],
      "items": [
        {
          "text": "A named, accountable outlet you could hold responsible shared it",
          "answer": 0
        },
        {
          "text": "The image is sharp, well-lit, and looks completely convincing",
          "answer": 1
        },
        {
          "text": "A second, unrelated source independently confirms the same thing",
          "answer": 0
        },
        {
          "text": "There's no \"Made with AI\" label on it",
          "answer": 1
        },
        {
          "text": "It's designed to make you furious and share it fast",
          "answer": 1
        },
        {
          "text": "An anonymous account made last month with 12 followers posted it",
          "answer": 1
        }
      ],
      "reveal": "Labels and watermarks feel like a safety net — but that's an analogy, not the real thing. Labels get applied inconsistently, watermarks can be cropped or stripped, and plenty of AI media has neither. A label's absence proves nothing, and its presence is just one weak clue. Only two things are real evidence: an accountable source, and independent confirmation. \"It looks real\" and \"engineered to make you furious\" are reasons to slow down, not to trust."
    },
    {
      "kind": "workflowChain",
      "title": "The three-question trust check",
      "goal": "Run the trust check on something you saw online, in order.",
      "correct": [
        "Who shared it? A named, accountable source you could hold responsible — or an anonymous, brand-new, no-name account?",
        "Can a second, independent source confirm it? If only one place says it, treat it as unconfirmed — not true.",
        "Is it built to make you furious or act fast? Content engineered to spike emotion is engineered to skip your judgment.",
        "Say a one-word verdict — trust, don't trust, or unconfirmed — and the specific reason behind it."
      ],
      "note": "The verdict has to rest on source and verification. \"Anonymous account plus no second source confirms it\" is a real reason. \"It looked real\" and \"there's no AI label\" are not."
    },
    {
      "kind": "tryLive",
      "title": "Run it on your own example",
      "prompt": "This optional step uses an external assistant, so anything entered leaves LearningAI. Use a public post or describe it without usernames, private messages, faces of private people, or location details. Help me evaluate this claim: [plain description]. Separate (1) who published it and whether they are accountable, (2) what a second independent source says, and (3) what remains unconfirmed. Do not judge truth from appearance or an AI label.",
      "note": "Choose a public headline, advertisement, or widely shared claim—not a private group-chat post. Open the original publisher and an independent source yourself. If the content asks for money, private information, or urgent action, stop and verify the sender through a route you already trust."
    },
    {
      "kind": "toolkitSave",
      "title": "Save your trust check",
      "cardType": "Trust check",
      "fields": [
        {
          "key": "content",
          "label": "What I saw",
          "placeholder": "e.g. a viral \"breaking news\" clip in a group chat"
        },
        {
          "key": "source",
          "label": "Who shared it (accountable?)",
          "placeholder": "e.g. anonymous account, made last month, 12 followers"
        },
        {
          "key": "confirm",
          "label": "Second independent source?",
          "placeholder": "e.g. no major outlet or fact-check page mentions it"
        },
        {
          "key": "verdict",
          "label": "Verdict + reason",
          "placeholder": "e.g. Unconfirmed — one anonymous source, nothing else confirms it"
        }
      ]
    },
    {
      "kind": "exitCheck",
      "title": "Give the verdict",
      "question": "A friend hands you a brand-new forwarded photo you've never analyzed. You give a verdict. Which answer shows you've got the skill?",
      "options": [
        {
          "text": "\"Don't trust it yet — unconfirmed. It came from a no-name account and no second, independent source confirms it.\"",
          "ok": true,
          "feedback": "Yes. Your reason is about source and verification, and you gave a clear verdict — exactly the check."
        },
        {
          "text": "\"Probably real: a known outlet reposted it, although I have not found the original report yet.\"",
          "ok": false,
          "feedback": "A known outlet is useful evidence, but a repost can still be wrong or stripped of context. Keep the verdict provisional until you open the underlying report or confirmation."
        },
        {
          "text": "\"Unconfirmed, but safe to share if I label it 'might be true.'\"",
          "ok": false,
          "feedback": "A warning label does not undo the spread or harm. If the consequential claim is unconfirmed, pause sharing."
        },
        {
          "text": "\"Two accounts repeat it, so that counts as two independent sources.\"",
          "ok": false,
          "feedback": "Two accounts may copy the same original claim. Independence means separate reporting or evidence, not repetition."
        }
      ]
    }
  ]
};
