// Lesson 29 — What Is Real Online Now
// Arc: Judgment & Safety
// Ported from Core 50 (auto-generated, then reviewed). Edit here, then run tools/build-lessons.mjs
export default {
  "id": "chapter-29",
  "num": 29,
  "arc": "Judgment & Safety",
  "title": "What Is Real Online Now",
  "coreQuestion": "How do I decide what to trust online when anything could be AI-made?",
  "blurb": "Stop trusting \"it looks real.\" Run a three-question trust check on who shared it and whether a second source confirms it.",
  "minutes": 9,
  "resources": [],
  "steps": [
    {
      "kind": "coldOpen",
      "title": "The flawless post",
      "scenario": "You scroll past a photo of a famous politician saying something shocking. The lighting is perfect. The voice matches. Thousands of people are already sharing it, furious. It feels completely real. The next day it turns out none of it happened — the whole clip was generated by AI.",
      "prompt": "Before you read on: if the clip looked and sounded flawless, what could you have checked to catch it — without relying on how real it looked?"
    },
    {
      "kind": "reveal",
      "title": "\"Looks real\" stopped being evidence",
      "body": "Here is the mechanism, not magic: image and video AI learned patterns from huge amounts of real media, and it produces new media that fits those patterns — the same way a text AI predicts the next word. It predicts what a convincing photo or clip would look like. That's why a photo, a voice, a news clip, even a five-star review can all be AI-made in 2026. The old test — \"if it looks and sounds real, it's real\" — no longer works. Its twin, \"I can always spot the fake,\" is worse: you can't reliably spot it anymore, and being sure you can is exactly what gets people fooled. The fix: assume anything online COULD be AI-made, and decide how much to trust it by who shared it and whether a second source confirms it — never by how convincing it looks.",
      "mistake": "Trusting a post because the details are perfect and it feels authentic — treating \"looks real\" as proof.",
      "good": "Treating every post as possibly AI-made, then checking the source and looking for a second, independent confirmation before you believe or share."
    },
    {
      "kind": "classify",
      "title": "Which clue actually helps?",
      "prompt": "Sort each thing into whether it's real evidence for trusting content, or a weak clue that proves nothing.",
      "buckets": [
        "Real evidence",
        "Weak clue / proves nothing"
      ],
      "items": [
        {
          "text": "A named, accountable outlet you could hold responsible shared it",
          "answer": 0
        },
        {
          "text": "The image is sharp, well-lit, and looks completely convincing",
          "answer": 1
        },
        {
          "text": "A second, unrelated source independently confirms the same thing",
          "answer": 0
        },
        {
          "text": "There's no \"Made with AI\" label on it",
          "answer": 1
        },
        {
          "text": "It's designed to make you furious and share it fast",
          "answer": 1
        },
        {
          "text": "An anonymous account made last month with 12 followers posted it",
          "answer": 1
        }
      ],
      "reveal": "Labels and watermarks feel like a safety net — but that's an analogy, not the real thing. Labels get applied inconsistently, watermarks can be cropped or stripped, and plenty of AI media has neither. A label's absence proves nothing, and its presence is just one weak clue. Only two things are real evidence: an accountable source, and independent confirmation. \"It looks real\" and \"engineered to make you furious\" are reasons to slow down, not to trust."
    },
    {
      "kind": "workflowChain",
      "title": "The three-question trust check",
      "goal": "Run the trust check on something you saw online, in order.",
      "correct": [
        "Who shared it? A named, accountable source you could hold responsible — or an anonymous, brand-new, no-name account?",
        "Can a second, independent source confirm it? If only one place says it, treat it as unconfirmed — not true.",
        "Is it built to make you furious or act fast? Content engineered to spike emotion is engineered to skip your judgment.",
        "Say a one-word verdict — trust, don't trust, or unconfirmed — and the specific reason behind it."
      ],
      "note": "The verdict has to rest on source and verification. \"Anonymous account plus no second source confirms it\" is a real reason. \"It looked real\" and \"there's no AI label\" are not."
    },
    {
      "kind": "tryLive",
      "title": "Run it on your own example",
      "prompt": "Here's something I saw online: [paste it or describe it plainly]. Walk me through whether it could be AI-made, then help me check whether it's trustworthy using two things: [who shared it — the account or outlet, and whether they're accountable] and whether a [second independent source] confirms it. Don't tell me it's real just because it looks real.",
      "note": "Pick ONE thing you genuinely saw in the last few days — an image, post, headline, or short clip. Example fills: \"a video of a politician saying something shocking\"; \"an account I'd never heard of, made last month, with 12 followers\"; \"I checked a major news site and a fact-check page — neither mentions it, so I'm treating it as unconfirmed.\" If it's about money, health, or an urgent request forwarded by a friend, also call that friend on a number you already have before you believe or share it."
    },
    {
      "kind": "toolkitSave",
      "title": "Save your trust check",
      "cardType": "Trust check",
      "fields": [
        {
          "key": "content",
          "label": "What I saw",
          "placeholder": "e.g. a viral \"breaking news\" clip in a group chat"
        },
        {
          "key": "source",
          "label": "Who shared it (accountable?)",
          "placeholder": "e.g. anonymous account, made last month, 12 followers"
        },
        {
          "key": "confirm",
          "label": "Second independent source?",
          "placeholder": "e.g. no major outlet or fact-check page mentions it"
        },
        {
          "key": "verdict",
          "label": "Verdict + reason",
          "placeholder": "e.g. Unconfirmed — one anonymous source, nothing else confirms it"
        }
      ]
    },
    {
      "kind": "exitCheck",
      "title": "Give the verdict",
      "question": "A friend hands you a brand-new forwarded photo you've never analyzed. You give a verdict. Which answer shows you've got the skill?",
      "options": [
        {
          "text": "\"Don't trust it yet — unconfirmed. It came from a no-name account and no second, independent source confirms it.\"",
          "ok": true,
          "feedback": "Yes. Your reason is about source and verification, and you gave a clear verdict — exactly the check."
        },
        {
          "text": "\"It's real — the detail is perfect and it looks completely convincing.\"",
          "ok": false,
          "feedback": "\"Looks real\" stopped being evidence. AI can make convincing media from patterns. Check the source and a second source instead."
        },
        {
          "text": "\"It's fine — there's no AI label or watermark on it.\"",
          "ok": false,
          "feedback": "A label's absence proves nothing — labels are inconsistent and watermarks can be stripped. The trust check is your test, not the label."
        },
        {
          "text": "\"I'll trust it — it made me so angry it has to be true.\"",
          "ok": false,
          "feedback": "Content built to spike emotion is built to skip your judgment. That's a reason to slow down, not to believe."
        }
      ]
    }
  ]
};
