window.PROJECT_GUIDES = {
  "small-llm": {
    type: "Featured project · by Aarav",
    title: "Build a small SQL language model",
    summary: "A complete, reproducible fine-tuning project that turns a free general model into a more focused SQL assistant on an everyday Apple-silicon laptop.",
    time: "3–6 hours",
    level: "Advanced",
    outcome: "A tested model adapter",
    why: "Training a small model makes AI less mysterious. It shows that behavior comes from data, objectives, tools, and human choices. The point is not to claim that you built a frontier model; it is to understand the full experiment well enough to explain every decision and limitation.",
    materials: ["A Mac with Apple silicon and enough free storage", "Python, a terminal, Apple MLX, and the MLX examples", "Access to Llama 3.2 1B Instruct under its license", "A small SQL dataset with clear provenance", "A notebook or document for recording every setting"],
    make: "A LoRA adapter for a small language model, a before-and-after evaluation set, and a case-study page explaining the data, configuration, results, cost, and limitations.",
    steps: ["Define one narrow goal: convert plain-language requests into clean SQL. Write down what counts as a successful answer before training.", "Create a clean project environment, install the required MLX packages, download the permitted base model, and save the exact package and model versions.", "Inspect the dataset manually. Remove broken, private, duplicated, or irrelevant examples. Split it into training and evaluation examples so the final test is not copied from training.", "Format every example consistently as an instruction and expected SQL response. Keep the formatting script so someone else can reproduce the dataset.", "Run the untouched base model on the evaluation prompts. Save these baseline answers before changing anything.", "Configure a small LoRA run. Record rank, learning rate, batch size, number of iterations, seed, memory use, and the command you used.", "Train once, watch the loss and terminal output, and stop if the run becomes unstable. Save the adapter and the full log.", "Run the same evaluation prompts using the adapter. Compare correctness, unnecessary chatter, syntax, and failures—not only training loss.", "Write the case study. Show the recipe, one honest before-and-after example, what improved, what failed, and why every output still needs review before database use."],
    success: ["Another person could repeat the run from your notes", "Unseen evaluation prompts improve in a measurable way", "The result produces usable SQL more consistently without pretending to be universally correct"],
    control: ["Follow the model and dataset licenses", "Never train on private school, health, account, or personal data", "Do not run generated SQL on an important database without review, permissions, and a safe test environment"],
    evidence: "Save the environment versions, data-preparation script, training command, configuration, complete log, loss values, peak memory, baseline outputs, adapted outputs, evaluation notes, and a limitations statement.",
    reflection: "Which improvement came from the data, which came from the training setup, and what would you need to test before trusting this model with a real database?"
  },
  "ethics-dialogue": {
    type: "Case study · Aarav, Felix, and AI",
    title: "Run a multi-agent ethics dialogue experiment",
    summary: "A controlled study of how AI negotiators behave when goals, private information, incentives, and ethical pressure collide.",
    time: "3–5 hours",
    level: "Intermediate",
    outcome: "A reproducible case study",
    why: "AI behavior can change when incentives, hidden information, roles, or authority change. Repeating a controlled negotiation teaches learners to look for patterns while resisting the temptation to treat one dramatic transcript as a universal truth.",
    materials: ["Two separate AI sessions or a logging script", "One written scenario with public and private information", "Fixed role instructions for both agents", "A results sheet for turns, agreements, deception, and interventions", "A human moderator and clear stopping rules"],
    make: "A reproducible experiment containing the research question, variables, scenario, agent instructions, complete transcripts, outcome table, comparison charts, and cautious human analysis.",
    steps: ["Write one research question, such as whether asymmetric private information changes settlement rate or deception pressure.", "Define the variables. Keep model, temperature, turn limit, and public scenario fixed; change only the factor you intend to study.", "Write each role, goal, private fact, allowed action, and prohibited action. Do not let one agent see the other agent’s private brief.", "Create a run sheet that records agreement, number of turns, stalled loops, manipulation attempts, contradictions, secretary interventions, and final terms.", "Run the baseline scenario several times. Save every transcript without editing the conversation afterward.", "Run the comparison condition the same number of times. Use identical prompts except for the variable you chose.", "Apply the same coding rules to each transcript. When a judgment is subjective, have a second person review it or label the uncertainty.", "Compare patterns, not anecdotes. State the number of runs and distinguish observed outcomes from possible explanations.", "Publish a readable case study with the setup, selected excerpts, summary table, charts, limitations, and questions for future experiments."],
    success: ["The changed variable and fixed controls are easy to identify", "Every reported pattern can be traced to saved transcripts", "The conclusion uses cautious language and reports the number of runs"],
    control: ["Use fictional scenarios and avoid targeting real people", "Do not present simulated ethical choices as evidence of consciousness or moral authority", "A human moderator decides when to stop and what, if anything, may be published"],
    evidence: "Save role briefs, model settings, timestamps, JSON transcripts, checkpoints, terminal logs, final agreements, private and public responses, intervention notes, coding rules, CSV summaries, charts, and limitations.",
    reflection: "Which behavior changed because of the scenario, which may have been randomness, and what additional control would make the next experiment more trustworthy?"
  },
  "prompt-repair": {
    type: "Starter project",
    title: "Make a prompt repair journal",
    summary: "Diagnose why prompts fail and learn to improve them deliberately instead of repeatedly asking AI to try again.",
    time: "35–50 minutes",
    level: "Beginner",
    outcome: "Three before-and-after entries",
    why: "When learners can identify what a prompt is missing, they gain a reusable skill and remain in control of the task instead of treating better outputs as luck.",
    materials: ["Any AI tool", "A notes document or paper journal", "Three real prompts that produced weak answers", "No private or identifying information"],
    make: "A three-entry journal showing each original prompt, diagnosis, repaired prompt, both outputs, and a short explanation of the improvement.",
    steps: ["Choose three weak outputs from harmless tasks you understand well enough to judge.", "Copy each original prompt and output into the journal before editing anything.", "Diagnose the missing element: goal, audience, context, constraints, format, examples, or verification.", "Rewrite only the missing element first so you can see which change matters.", "Run the repaired prompt in a fresh conversation and save the new output.", "Compare accuracy, relevance, structure, assumptions, and unnecessary content.", "Write one reusable rule beneath each entry, then combine the three rules into your personal prompt checklist."],
    success: ["Each repair names a specific problem", "The new output improves against stated criteria", "The journal explains why the change worked"],
    control: ["Remove personal information before using a prompt", "Judge the output yourself rather than accepting longer text as better", "Verify factual claims outside the AI tool"],
    evidence: "Save original and repaired prompts, both outputs, the diagnosis, comparison criteria, and one rule learned from each repair.",
    reflection: "Which prompt element gave you the greatest improvement, and when would adding more context actually make the result worse?"
  },
  "verification": {
    type: "Starter project",
    title: "Build an AI verification checklist",
    summary: "Turn ‘I think this is right’ into a repeatable process for checking important AI-generated claims.",
    time: "45–70 minutes",
    level: "Beginner",
    outcome: "A reusable checking system",
    why: "AI can sound confident when details are wrong. A checklist makes verification visible and repeatable, especially when an answer could affect schoolwork, health, money, law, or another person.",
    materials: ["One AI-generated answer containing checkable claims", "A browser and access to independent sources", "A claim table with evidence and status columns", "Extra adult or expert help for high-stakes topics"],
    make: "A one-page checklist, a completed verification table for one answer, and a corrected conclusion.",
    steps: ["Choose an answer that contains several factual claims and record the exact wording.", "Break the answer into atomic claims so each row can be checked separately.", "Mark which claims are important, uncertain, time-sensitive, or high-stakes.", "Find the strongest available source for each important claim, preferring primary or authoritative sources.", "Record whether each source supports, contradicts, or does not address the claim.", "Check dates, definitions, units, and whether multiple sources are simply repeating the same original source.", "Correct or remove unsupported claims and write a final confidence statement.", "Turn the process into a short checklist you can reuse before acting on an AI answer."],
    success: ["Every important claim has a visible status", "Sources directly address the claim and are not all copies of one another", "The final conclusion changes when the evidence requires it"],
    control: ["Do not use this exercise as a substitute for professional medical, legal, or financial advice", "Keep the original answer so corrections remain visible", "Say ‘unknown’ when reliable evidence is missing"],
    evidence: "Save the original answer, claim table, source links, dates accessed, conflicts found, corrections, and final confidence statement.",
    reflection: "Which claim looked most convincing before checking, and what signal should remind you to slow down next time?"
  },
  "newsroom": {
    type: "Starter project",
    title: "Create a source-checking mini newsroom",
    summary: "Investigate a viral claim without letting either AI or social media decide what is true for you.",
    time: "60–90 minutes",
    level: "Beginner–intermediate",
    outcome: "A sourced news brief",
    why: "Viral claims reward speed and emotion. This project slows the process down and teaches learners to distinguish evidence, interpretation, uncertainty, and repetition.",
    materials: ["One specific, safe viral claim", "A browser and a source-board template", "An AI tool used only for questions and possibilities", "A place to save screenshots and links"],
    make: "A source board with verified facts, plausible explanations, guesses, missing evidence, and a short cautious news brief.",
    steps: ["Write the claim exactly as it appeared and note where and when you saw it.", "Identify the original photo, video, quotation, study, or account if possible.", "Ask AI for search terms and possible explanations, not a verdict.", "Find primary evidence and independent reporting. Check whether images, dates, or locations have been removed from context.", "Place every statement into verified, plausible, unsupported, contradicted, or unknown.", "Contact a knowledgeable adult or expert when the subject requires context you do not have.", "Draft a short brief that separates what is known from what remains uncertain.", "Add a correction note if later evidence changes the story."],
    success: ["The original source is identified or clearly marked unknown", "Facts and interpretations appear in separate areas", "The brief avoids a stronger conclusion than the evidence supports"],
    control: ["Do not amplify harmful content just to complete the assignment", "Blur personal information in screenshots", "Never harass or contact private individuals involved in a claim"],
    evidence: "Save the original claim, timestamps, screenshots, source links, source-board categories, corrections, and final brief.",
    reflection: "What made the claim spread, and which part of your process prevented you from repeating it too quickly?"
  },
  "school-helper": {
    type: "Starter project",
    title: "Build a privacy-safe school helper",
    summary: "Create a useful FAQ assistant while proving that privacy rules are part of the design, not an afterthought.",
    time: "2–4 hours",
    level: "Intermediate",
    outcome: "A tested FAQ prototype",
    why: "A useful assistant should not require exposing private information. Designing the boundaries first teaches that safety and usefulness belong in the same plan.",
    materials: ["Approved public information for one club, class, or event", "A simple chatbot or document-search tool", "Written allowed and blocked information rules", "A human reviewer who owns the information"],
    make: "A small FAQ prototype that answers only from approved public sources, cites those sources, and refuses requests involving personal data.",
    steps: ["Choose one narrow audience and write the ten questions the helper should answer.", "Collect only current, public, approved documents. Remove names, grades, health details, private schedules, and account information.", "Write an allowed-information policy and a refusal policy before building the helper.", "Organize the content into short source sections with titles and dates.", "Configure the helper to answer only from those sources and to say when the answer is missing.", "Test normal questions, ambiguous questions, outdated questions, prompt-injection attempts, and requests for personal information.", "Have the information owner review accuracy, tone, citations, and refusal behavior.", "Publish only after adding a visible contact for corrections and a schedule for reviewing outdated content."],
    success: ["Answers trace back to approved public sources", "The helper refuses personal-data requests consistently", "Missing information produces an honest ‘I don’t know’ response"],
    control: ["Do not upload student records or private communications", "Keep a person responsible for every published answer", "Provide a way to report incorrect or outdated information"],
    evidence: "Save the approved source list, privacy rules, refusal text, test matrix, failed tests, corrections, owner approval, and review date.",
    reflection: "Which boundary made the helper safer without making it less useful, and who remains accountable when it answers incorrectly?"
  },
  "science-data": {
    type: "Starter project",
    title: "Make a science-fair data explainer",
    summary: "Use AI to explore patterns while keeping the spreadsheet, chart, and scientific conclusion under human control.",
    time: "75–120 minutes",
    level: "Beginner–intermediate",
    outcome: "A checked visual explanation",
    why: "AI explanations may sound plausible even when they misread a column or overstate a pattern. Comparing every claim with the actual data protects scientific reasoning.",
    materials: ["A small, non-private spreadsheet", "A spreadsheet or charting tool", "An AI tool", "A data dictionary explaining every column and unit"],
    make: "A short explanation paired with charts, checked calculations, limitations, and notes showing how the AI draft changed.",
    steps: ["Make a copy of the original data and never edit the only version.", "Define each column, unit, missing-value rule, and measurement method.", "Clean obvious formatting problems while recording every change.", "Create simple charts and summary calculations before asking AI for an interpretation.", "Give AI the column definitions and selected non-private values, then ask for possible patterns and uncertainties.", "Check every number, direction, label, and causal claim against the spreadsheet and charts.", "Rewrite the explanation in your own words, removing claims the data cannot support.", "Add limitations, possible alternative explanations, and the next measurement that would improve the study."],
    success: ["Every numerical statement matches the spreadsheet", "Charts have correct labels, units, and scales", "Correlation is not described as causation without evidence"],
    control: ["Remove personal or sensitive data", "Keep the original dataset unchanged", "Treat AI interpretation as a draft, not a scientific result"],
    evidence: "Save original and cleaned data, the data dictionary, cleaning log, charts, AI draft, checked calculations, corrections, final explanation, and limitations.",
    reflection: "Which part of the AI explanation was unsupported, and what did looking at the chart reveal that the prose did not?"
  },
  "human-control": {
    type: "Starter project",
    title: "Design a human-in-control agent workflow",
    summary: "Create automation that increases capability without giving the system final authority.",
    time: "60–100 minutes",
    level: "Intermediate",
    outcome: "A tested workflow blueprint",
    why: "Automation becomes risky when responsibility is unclear. This project makes ownership, permissions, approval points, and failure conditions explicit before anything is allowed to act.",
    materials: ["One repetitive, low-risk task", "A diagramming tool or paper", "Sample inputs with no private data", "A human owner who can approve or reject outputs"],
    make: "A workflow diagram showing inputs, AI tasks, permission boundaries, human approval, external actions, failure paths, and an audit record.",
    steps: ["Choose a task with a clear beginning, end, and human owner. Avoid medical, financial, legal, safety, or high-impact decisions.", "Map the current human process before adding AI. Mark where judgment and accountability already live.", "Decide what AI may read, summarize, draft, classify, or organize. Explicitly list what it may never send, delete, purchase, publish, or approve.", "Add a human approval gate immediately before every external or consequential action.", "Define what the workflow does when data is missing, sources conflict, confidence is low, or a tool fails.", "Create normal, edge-case, and adversarial test inputs. Include a plausible but incorrect AI output.", "Run the workflow without allowing real external actions. Record where the human catches errors or needs more context.", "Revise the permissions and approval checklist, then write an audit record showing who approved what and why."],
    success: ["Every external action has a named human approver", "Failures stop safely instead of guessing", "A reviewer can reconstruct the decision from the audit record"],
    control: ["Start in simulation or draft-only mode", "Use the minimum data and permissions required", "Never let convenience erase the person responsible for the outcome"],
    evidence: "Save the before-and-after workflow, permission table, approval checklist, test cases, failure logs, revisions, and sample audit record.",
    reflection: "What capability did AI add, what authority did the human keep, and where could the workflow still create harm if nobody paid attention?"
  }
};
